apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: software-installation
  title: Software Installation
spec:
  owner: team-platform
  type: service

  parameters:
    - title: Software 
      required:
        - SoftwareName
      properties:
        SoftwareName:
          type: string
          title: Software name
          enum:
            - Postgresql
            - Nginx
            - Grafana

      dependencies:
        SoftwareName:
          oneOf:
            - properties:
                SoftwareName:
                  const: Postgresql
                Softwareversion:
                  type: string
                  title: Choisissez une version
                  enum:
                    - v13
                    - v14
                    - v16
              required:
                - Softwareversion

            - properties:
                SoftwareName:
                  const: Nginx
                Softwareversion:
                  type: string
                  title: Choisissez une version
                  enum:
                    - v2.4
                    - v2.5
                    - v2.6
              required:
                - Softwareversion

            - properties:
                SoftwareName:
                  const: Grafana
                Softwareversion:
                  type: string
                  title: Choisissez une version
                  enum:
                    - v2
                    - v3
                    - v4
              required:
                - Softwareversion
                
  steps:
    - id: launch-job
      name: Launch Job Template
      action: rhaap:launch-job-template
      input:
        token: ${{ parameters.AAP_TOKEN }}
        values:
          template: test job
